```{r library, include=FALSE}
# locally Install protti

my_packages <- c("tidyverse", "data.table", "readxl",
                 "protti")
pacman::p_load(char = my_packages)

tmp <- list()
```

requirement for input peptides data:
1) include PK or without PK data;
2) Peptide abundances data normally with "Abundances" or "Intensity";
3) With Sequence, Protein Accessions info;
4) May with match genenames, and modification info.

source main function:
```{r}
source("example_analysis_function.R")
```

load gene protein transform data:
```{r}
gene_protein_df <- fread("Input/Human_protein_gene_id.csv")
colnames(gene_protein_df) <- c("Accession", "GeneName")
gene_protein_df$`UniProtKB-ID` <- NULL
```

Run:
```{r}
# raw_peptide <- readxl::read_xlsx("Input/20241201_DDA_SFY_ALL_PEPTIDES.xlsx", sheet = 1)
# Preprocess:
raw_peptide <- fread("Input/lipMs_test-Peng-0313.csv")
raw_peptide2 <- preprocess_raw_peptide(raw_peptide)

modifications_df <- unique(
  raw_peptide2[,c("precursor", "Modifications")]
) %>% na.omit()

peptides_list <- transfer_maxquant_data(raw_peptide2)

# One command run:
peptides_diff <- run_lip_ms_analysis(peptides_list,
                    modifications_df = modifications_df)
```

# Save
```{r}

```

